### PR TITLE
remove largely useless Utils class

### PR DESCRIPTION
**Pull request by lamont-granquist**
its just a collection of private methods, they should be private methods

### CODE REVIEW

**Comment by coderanger** [comment]
Sooooo I'm actually using one of those :-/ https://github.com/poise/poise/blob/master/lib/poise/utils/win32.rb#L116

**Comment by lamont-granquist** [comment]
lol, 'k

**Comment by coderanger** [comment]
Works for me, I can switch over my code to do a feature detect on it easily enough so we can nuke the stub eventually.

**Comment by lamont-granquist** [comment]
doesn't pass in your tests right now, i'm sure i've just got some thinko/typo somewhere...

**Comment by lamont-granquist** [comment]
oic what the issue is...

**Comment by lamont-granquist** [comment]
@coderanger fixed and squashed, passes your tests, can i get a 👍 ?

**Pull request merged**
