### PR TITLE
Fix #111

### LINKED ISSUE #111: CreateProcessW(): Invalid access to memory location
I'm getting these errors randomly (and hard to reproduce) on my boxen:

```
Chef::Exceptions::MultipleFailures: Multiple failures occurred:
* SystemCallError occurred in chef run: powershell_script[ssl-cert: permissions] (bigdatalab-role-windows::_ssl_cert line 47) had an error: SystemCallError: Invalid access to memory location. - CreateProcessW
* SystemCallError occurred in delayed notification: windows_task[\chef-client] (chef-client::task line 32) had an error: SystemCallError: Invalid access to memory location. - CreateProcessW


C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.1.0-universal-mingw32/lib/mixlib/shellout/windows/core_ext.rb:346:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.1.0-universal-mingw32/lib/mixlib/shellout/windows.rb:86:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.1.0-universal-mingw32/lib/mixlib/shellout.rb:259:in `run_command'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:97:in `shell_out_command'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:50:in `shell_out'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:55:in `shell_out!'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/powershell_script.rb:79:in `block in validate_script_syntax!'
C:/opscode/chef/embedded/lib/ruby/2.0.0/tempfile.rb:324:in `open'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/powershell_script.rb:64:in `validate_script_syntax!'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/powershell_script.rb:33:in `action_run'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:140:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:584:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:654:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:649:in `catch'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:649:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:688:in `converge_and_save'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:269:in `run'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:229:in `block in run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:375:in `run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:67:in `load'
C:/opscode/chef/bin/chef-client:67:in `<main>'
```

They don't happen at any particular recipe for any particular cookbook. That is, they are pretty random.

What I think is happening is that `CreateProcessW()` is passing in a "constant" version of `cmd`.  According to the [MSDN Documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx)'s for `lpCommandLine`:

> The Unicode version of this function, `CreateProcessW`, can modify the contents of this string. Therefore, this parameter cannot be a pointer to read-only memory (such as a const variable or a literal string). If this parameter is a constant string, the function may cause an access violation.

The error message "Invalid access to memory location" is consistent with the second argument (`lpCommandLine`) being within read-only memory.

I think the fix is to change [`core_ext.rb` line 226](https://github.com/chef/mixlib-shellout/blob/2-stable/lib/mixlib/shellout/windows/core_ext.rb#L226) to use an allocated bit of memory:

``` rb
    if hash['command_line']
      cmd = FFI::MemoryPointer.new(:string, 1024)
      cmd.write_string hash['command_line'].to_wide_string
    end
```

I'm not sure `1024` is the right value.  Other examples I have seen use things like (reverting to C/C++) the following:

~~~ c++
WCHAR lpCommandLine[MAX_PATH * 2];
/* Make a copy of cmd so CreateProcessW() can modify it if it needs to. */
_tcscpy_s(lpCommandLine, MAX_PATH *2, (WCHAR *)cmd);
~~~

or

~~~ c++
// http://stackoverflow.com/questions/4514027/createprocessw-acess-violation-in-rtlinitunicodestring

//I'm copying the string here because CreateProcessW mutates its arguments
wchar_t *lpCommandLine = _wcsdup(cmd);
...
free(lpCommandLine);
~~~

If it helps, there is a Microsoft blog post about why `CreateProccesW()` has historically had this behavior: http://blogs.msdn.com/b/oldnewthing/archive/2009/06/01/9673254.aspx

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by chefsalim** [comment]
Can you explain the core fix here - are these several un-related changes?

**Comment by ksubrama** [comment]
The three separate commits should isolate the changes.  Also view the change with ?w=1 - because the majority of it is a whitespace change.

The first just bumps our upstream version of win32-process with an updated FFI binding.  The second copies over all the fixes needed to use the new bindings from the upstream file linked in the comments.  The third was more of a "why are we doing this strange stuff here - I don't think this is right..." fixup and should be double checked.  All the tests pass - so that's a good thing :)

**Comment by chefsalim** [comment]
OK.. #1 and #2 LGTM.  I don't fully understand the implications of #3.. what is the behavior without that change, and is the fix something we should submit upstream?

**Comment by ksubrama** [comment]
#3 - It's not supposed to really change the behavior.  Well - the original might have had a few more weird methods in the singleton classes of some of these modules but I don't think it has any practical difference.  #3 is just changing how we monkey patch - so there's nothing to contribute upstream.  Our own edits  in create() might be something we can contribute but that's a bunch of extra work to write tests specifically for it and making sure our behavior is what everyone would want etc.

**Pull request merged**
