### PR TITLE
Remove dependency on windows-pr

### PR DESCRIPTION
**Pull request by jaym**
windows-pr includes everything under the sun.
This is means it does not work no nanoserver

cc @adamedx @chefsalim @ksubrama @mcquin

### CODE REVIEW

**Comment by jaym** [comment]
test fails on master as well. No idea why, passes on my machine

**Comment by jaym** [comment]
This seems to be an issue with ruby `2.0.0p645`. `2.0.0p598` has no issues

**Comment by jaym** [comment]
Fixed test in https://github.com/chef/mixlib-shellout/pull/103

**Comment by ksubrama** [comment]
:+1: :icecream:

**Comment by lamont-granquist** [comment]
That is really odd, but its fine, you're still testing that the thing works.

**Comment by lamont-granquist** [comment]
:+1:

**Comment by lamont-granquist** [comment]
erm, those comments were for #103 which i see you've already merged...

**Comment by jaym** [comment]
What's specifically odd?

**Comment by jaym** [comment]
ahh, got it

**Comment by lamont-granquist** [comment]
i don't know enough about windows to know if those constants are always constant or whatever, but if you extracted that directly from windows-pr and that's all we need then, yes, :+1:

**Comment by danielsdeleo** [comment]
:+1:

**Comment by jaym** [comment]
they're constants that are included in the windows header files. I doubt MSFT could ever change them without breaking the world

**Comment by lamont-granquist** [comment]
excellent

**Pull request merged**
