### PR TITLE
Bump version to 2.2.0

### PR DESCRIPTION
**Pull request by jaym**
Thoughts on release this gem?
cc @lamont-granquist @thommay @danielsdeleo

### CODE REVIEW

**Comment by danielsdeleo** [comment]
Is the changelog correct, we just got rid of `windows-pr` ?

**Comment by jaym** [comment]
Yea, the git history seems to indicate that's all that happened

**Comment by danielsdeleo** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Pull request merged**
